          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.html_url }} --merge --delete-branch || \
          gh pr merge ${{ github.event.pull_request.html_url }} --merge --admin --delete-branch